# Generated by Django 6.0.4 on 2026-05-20 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('lesson', '0001_initial'),
        ('quiz', '0003_quiztemplate_shuffle_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_score_percent', models.PositiveSmallIntegerField(default=70)),
                ('is_required', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=0, help_text='0 = unlimited.')),
                ('unlock_next_lesson_on_success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_quiz', to='course.course')),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_quiz', to='lesson.lesson')),
                ('quiz_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_validations', to='quiz.quiztemplate')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', True), ('lesson__isnull', False)), models.Q(('course__isnull', False), ('lesson__isnull', True)), _connector='OR'), name='lessonquiz_exactly_one_target')],
            },
        ),
    ]
