# Generated by Django 6.0.4 on 2026-05-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonquiz',
            name='is_required',
        ),
    ]
