# Generated by Django 6.0.4 on 2026-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
