# Generated by Django 6.0.6 on 2026-07-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_certificate_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='expiry_reminder_30d_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='expiry_reminder_7d_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
