# Generated by Django 6.0.4 on 2026-04-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_rename_staff_to_managers'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['domain', 'active'], name='subject_domain_active_idx'),
        ),
    ]
