# Generated by Django 6.0.7 on 2026-07-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjecttranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subjecttranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='subject_subject_translation_uniq_lang'),
        ),
    ]
