# Generated by Django 6.0.4 on 2026-05-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_enrollment', '0004_courseinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinvite',
            name='inviter',
        ),
    ]
