# Generated by Django 6.0.4 on 2026-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_enrollment', '0005_remove_courseinvite_inviter'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinvite',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
