# Generated by Django 6.0.4 on 2026-05-20 07:32

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_preview', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('estimated_duration', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.section')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LessonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('short_description', models.TextField(blank=True, verbose_name='short description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lesson.lesson')),
            ],
            options={
                'verbose_name': 'lesson Translation',
                'db_table': 'lesson_lesson_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('section', 'slug'), name='uniq_lesson_slug_per_section'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='uniq_lesson_order_per_section'),
        ),
        migrations.AlterUniqueTogether(
            name='lessontranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
