# Generated by Django 6.0.4 on 2026-05-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
