# Generated by Django 6.0.4 on 2026-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_validity_months',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = no expiration.'),
        ),
        migrations.AddField(
            model_name='course',
            name='issues_certificate',
            field=models.BooleanField(default=True),
        ),
    ]
