# Generated by Django 6.0.6 on 2026-07-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_certificate_validity_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate_validity_months',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Never (lifetime)'), (12, '1 year'), (24, '2 years'), (60, '5 years'), (120, '10 years')], default=0, help_text='0 = never expires (lifetime).'),
        ),
    ]
