# Generated by Django 6.0.7 on 2026-07-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_certificate_validity_months'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursetranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sectiontranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coursetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='course_course_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='sectiontranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='course_section_translation_uniq_lang'),
        ),
    ]
