# Generated by Django 6.0.4 on 2026-05-20 10:04
#
# Polymorphic Block schema (Phase 2 of the LMS refactor):
# ``Block`` no longer carries a plain ``lesson`` FK — every row is now
# attached to its host via ``(target_content_type, target_object_id)``
# and resolved through the ``target`` GenericForeignKey on the model.
#
# Production migration concern: this branch is fresh-DB; on merge to
# main, existing ``lms_catalog_contentblock`` rows must be backfilled
# with ``target_content_type=ContentType.objects.get_for_model(Lesson)``
# and ``target_object_id=<lesson_id>`` before the old ``lesson`` FK
# column is dropped. Write the backfill SQL in
# ``deploy/migrate-lms-split.sql`` ahead of the merge.

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quiz', '0003_quiztemplate_shuffle_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.BigIntegerField()),
                ('block_type', models.CharField(choices=[('rich_text', 'Rich text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('quiz', 'Quiz'), ('callout', 'Callout'), ('code', 'Code'), ('embed', 'Embed')], max_length=16)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lms/blocks/img/')),
                ('video_url', models.URLField(blank=True)),
                ('video_provider', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('upload', 'Self-hosted')], max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='lms/blocks/file/')),
                ('external_url', models.URLField(blank=True)),
                ('code_language', models.CharField(blank=True, max_length=32)),
                ('code_content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('quiz_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_blocks', to='quiz.quiztemplate')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_hosts', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['target_content_type', 'target_object_id', 'order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('rich_text', models.TextField(blank=True, verbose_name='rich text')),
                ('callout_text', models.TextField(blank=True, verbose_name='callout text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='block.block')),
            ],
            options={
                'verbose_name': 'block Translation',
                'db_table': 'block_block_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='block_block_target__9cefd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('target_content_type', 'target_object_id', 'order'), name='uniq_block_order_per_target'),
        ),
        migrations.AlterUniqueTogether(
            name='blocktranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
