# Generated by Django 6.0.4 on 2026-05-20 07:32

import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('rich_text', 'Rich text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('quiz', 'Quiz'), ('callout', 'Callout'), ('code', 'Code'), ('embed', 'Embed')], max_length=16)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lms/blocks/img/')),
                ('video_url', models.URLField(blank=True)),
                ('video_provider', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('upload', 'Self-hosted')], max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='lms/blocks/file/')),
                ('external_url', models.URLField(blank=True)),
                ('code_language', models.CharField(blank=True, max_length=32)),
                ('code_content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContentBlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('rich_text', models.TextField(blank=True, verbose_name='rich text')),
                ('callout_text', models.TextField(blank=True, verbose_name='callout text')),
            ],
            options={
                'verbose_name': 'content block Translation',
                'db_table': 'block_contentblock_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
