# Generated by Django 6.0.4 on 2026-05-20 07:32

import django.db.models.deletion
import parler.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('block', '0001_initial'),
        ('lesson', '0001_initial'),
        ('quiz', '0003_quiztemplate_shuffle_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='lesson.lesson'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='quiz_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_blocks', to='quiz.quiztemplate'),
        ),
        migrations.AddField(
            model_name='contentblocktranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='block.contentblock'),
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='uniq_block_order_per_lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='contentblocktranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
