#!/usr/bin/env bash
#
# QuizOnline — fetch frontend Sentry runtime config from SSM.
#
# Reads three parameters under ``$PREFIX`` (default ``/quizonline/prod``)
# and writes a nginx snippet at
# ``/etc/nginx/snippets/quizonline-frontend-runtime.conf``. Reloads
# nginx if (and only if) the snippet content changed.
#
# Parameters read:
#   $PREFIX/SENTRY_FRONTEND_DSN     — SecureString, empty = SDK off
#   $PREFIX/SENTRY_FRONTEND_ENV     — String, default "production"
#   $PREFIX/SENTRY_FRONTEND_RELEASE — String, default ""
#   $PREFIX/TURNSTILE_SITE_KEY      — String (public), empty = captcha off
#
# Invoked at boot by quizonline-frontend-runtime-fetch.service, and
# re-invoked at the tail of every CI deploy so a rotation of the SSM
# parameter is picked up without an SSH round trip.
#
# A missing/empty DSN parameter is treated as "no reporting" — the
# snippet is written with empty values, the nginx default-empty
# ``set $sentry_dsn ""`` in the server block is overridden by these
# empty values (a no-op), and the inline SDK init is a no-op. This
# keeps the system in a known state even when no reporting endpoint
# is configured (e.g. during bootstrap before the SSM param exists).
#
# Auth: relies on the EC2 instance role having ``ssm:GetParameter``
# on the three names. No credentials on disk.
set -euo pipefail

PREFIX="${QOL_SSM_PREFIX:-/quizonline/prod}"
REGION="${QOL_SSM_REGION:-eu-west-1}"
OUT_FILE="${QOL_FRONTEND_RUNTIME_FILE:-/etc/nginx/snippets/quizonline-frontend-runtime.conf}"

echo "[frontend-runtime] prefix=$PREFIX region=$REGION out=$OUT_FILE"

# Single-parameter fetch with a sane default when the param doesn't
# exist or the call fails (e.g. IAM hiccup). We could distinguish
# "ParameterNotFound" from "AccessDenied" by parsing stderr, but the
# downstream effect is the same — empty value, SDK no-op — so the
# simpler unified path is preferred.
fetch_one() {
  local key="$1"
  local default="${2:-}"
  local value
  if value=$(aws ssm get-parameter \
        --region "$REGION" \
        --name "$PREFIX/$key" \
        --with-decryption \
        --query 'Parameter.Value' \
        --output text 2>/dev/null); then
    printf '%s' "$value"
  else
    echo "[frontend-runtime] $key not in SSM — using default '$default'" >&2
    printf '%s' "$default"
  fi
}

DSN=$(fetch_one SENTRY_FRONTEND_DSN "")
ENVNAME=$(fetch_one SENTRY_FRONTEND_ENV "production")
RELEASE=$(fetch_one SENTRY_FRONTEND_RELEASE "")
# Public Cloudflare Turnstile site key (captcha on register + password reset).
# Same parameter the backend reads (/quizonline/prod/TURNSTILE_SITE_KEY); empty
# = captcha not provisioned, so the frontend hides the widget.
TURNSTILE_SITE_KEY=$(fetch_one TURNSTILE_SITE_KEY "")

# Refuse values with embedded newlines — nginx would parse them
# weirdly (the ``set`` directive expects a single token) and a well-
# formed DSN/env/release/site-key never contains them.
for var in DSN ENVNAME RELEASE TURNSTILE_SITE_KEY; do
  case "${!var}" in
    *$'\n'*|*$'\r'*)
      echo "ERROR: $var contains a newline character" >&2
      exit 2
      ;;
  esac
done

TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

cat > "$TMP_FILE" <<EOF
# AUTO-GENERATED by deploy/fetch-frontend-runtime-from-ssm.sh
# Source of truth: AWS SSM Parameter Store at $PREFIX/SENTRY_FRONTEND_* + TURNSTILE_SITE_KEY
# Manual edits will be overwritten on the next service restart / boot.

set \$sentry_dsn "$DSN";
set \$sentry_env "$ENVNAME";
set \$sentry_release "$RELEASE";
set \$turnstile_site_key "$TURNSTILE_SITE_KEY";
EOF

# Idempotency: nothing to do if the snippet already matches. Skips the
# nginx reload, which is cheap but not free (worker recycling).
if [ -f "$OUT_FILE" ] && cmp -s "$TMP_FILE" "$OUT_FILE"; then
  echo "[frontend-runtime] $OUT_FILE unchanged — no reload needed"
  exit 0
fi

mkdir -p "$(dirname "$OUT_FILE")"
install -m 0644 -o root -g root "$TMP_FILE" "$OUT_FILE"
echo "[frontend-runtime] $OUT_FILE updated"

# Guard: validate the full nginx config (server block + this snippet)
# before reloading. If anything is wrong (mis-quoted value, missing
# parent directive after a future template change…), abort while the
# running master is still on the previous config.
if ! nginx -t; then
  echo "ERROR: nginx -t failed after writing $OUT_FILE — skipping reload" >&2
  exit 3
fi

systemctl reload nginx
echo "[frontend-runtime] nginx reloaded"
