#!/usr/bin/env bash
#
# QuizOnline — fetch frontend Sentry runtime config from SSM.
#
# Reads three parameters under ``$PREFIX`` (default ``/quizonline/prod``)
# and writes a nginx snippet at
# ``/etc/nginx/snippets/quizonline-frontend-runtime.conf``. Reloads
# nginx if (and only if) the snippet content changed.
#
# Parameters read from /quizonline-frontend/prod (bare names):
#   SENTRY_DSN          — String (DSN ships in the SPA), empty = SDK off
#   SENTRY_ENV          — String, default "production"
#   SENTRY_RELEASE      — String, default ""
#   TURNSTILE_SITE_KEY  — String (public), empty = captcha off
#
# Invoked at boot by quizonline-frontend-runtime-fetch.service, and
# re-invoked at the tail of every CI deploy so a rotation of the SSM
# parameter is picked up without an SSH round trip.
#
# A missing/empty DSN parameter is treated as "no reporting" — the
# snippet is written with empty values, the nginx default-empty
# ``set $sentry_dsn ""`` in the server block is overridden by these
# empty values (a no-op), and the inline SDK init is a no-op. This
# keeps the system in a known state even when no reporting endpoint
# is configured (e.g. during bootstrap before the SSM param exists).
#
# Auth: relies on the EC2 instance role having ``ssm:GetParameter``
# on the three names. No credentials on disk.
set -euo pipefail

# Dedicated /quizonline-frontend/prod prefix with BARE names, like
# pushit-frontend / tm-frontend (OPERATIONS.md §3.14).
PREFIX="${QOL_FRONTEND_SSM_PREFIX:-/quizonline-frontend/prod}"
REGION="${QOL_SSM_REGION:-eu-west-1}"
OUT_FILE="${QOL_FRONTEND_RUNTIME_FILE:-/etc/nginx/snippets/quizonline-frontend-runtime.conf}"

echo "[frontend-runtime] prefix=$PREFIX region=$REGION out=$OUT_FILE"

# Read one SSM String with a default; empty on ParameterNotFound/AccessDenied
# (downstream no-op — the SDK just stays disabled / the widget hides).
fetch_one() {
  local value
  value=$(aws ssm get-parameter --region "$REGION" --name "$PREFIX/$1" \
    --with-decryption --query 'Parameter.Value' --output text 2>/dev/null) || value="${2:-}"
  printf '%s' "$value"
}

DSN=$(fetch_one SENTRY_DSN "")
ENVNAME=$(fetch_one SENTRY_ENV "production")
RELEASE=$(fetch_one SENTRY_RELEASE "")
TURNSTILE_SITE_KEY=$(fetch_one TURNSTILE_SITE_KEY "")

# Refuse values with embedded newlines — nginx would parse them
# weirdly (the ``set`` directive expects a single token) and a well-
# formed DSN/env/release/site-key never contains them.
for var in DSN ENVNAME RELEASE TURNSTILE_SITE_KEY; do
  case "${!var}" in
    *$'\n'*|*$'\r'*)
      echo "ERROR: $var contains a newline character" >&2
      exit 2
      ;;
  esac
done

TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

cat > "$TMP_FILE" <<EOF
# AUTO-GENERATED by deploy/fetch-frontend-runtime-from-ssm.sh
# Source of truth: AWS SSM $PREFIX/* (bare names)
# Manual edits will be overwritten on the next service restart / boot.

set \$sentry_dsn "$DSN";
set \$sentry_env "$ENVNAME";
set \$sentry_release "$RELEASE";
set \$turnstile_site_key "$TURNSTILE_SITE_KEY";
EOF

# Idempotency: nothing to do if the snippet already matches. Skips the
# nginx reload, which is cheap but not free (worker recycling).
if [ -f "$OUT_FILE" ] && cmp -s "$TMP_FILE" "$OUT_FILE"; then
  echo "[frontend-runtime] $OUT_FILE unchanged — no reload needed"
  exit 0
fi

mkdir -p "$(dirname "$OUT_FILE")"
install -m 0644 -o root -g root "$TMP_FILE" "$OUT_FILE"
echo "[frontend-runtime] $OUT_FILE updated"

# Guard: validate the full nginx config (server block + this snippet)
# before reloading. If anything is wrong (mis-quoted value, missing
# parent directive after a future template change…), abort while the
# running master is still on the previous config.
if ! nginx -t; then
  echo "ERROR: nginx -t failed after writing $OUT_FILE — skipping reload" >&2
  exit 3
fi

systemctl reload nginx
echo "[frontend-runtime] nginx reloaded"
