# Generated by Django 6.0.4 on 2026-05-17 23:20

import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0006_domain_notification_settings'),
        ('language', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='lms/covers/')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=16)),
                ('estimated_duration', models.PositiveIntegerField(default=0, help_text='Total expected duration in minutes.')),
                ('enrollment_mode', models.CharField(choices=[('open', 'Open enrollment'), ('approval', 'Requires approval'), ('invite', 'Invite-only')], default='open', max_length=16)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='domain.domain')),
                ('language', models.ForeignKey(help_text='Primary language of the course.', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='language.language')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('learning_objectives', models.TextField(blank=True, verbose_name='learning objectives')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lms_catalog.course')),
            ],
            options={
                'verbose_name': 'course Translation',
                'db_table': 'lms_catalog_course_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['domain', 'is_published'], name='lms_catalog_domain__8449c2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='lms_catalog_slug_68a2bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
