# Generated by Django 6.0.4 on 2026-05-17 23:27

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_catalog', '0003_lesson_lessontranslation_and_more'),
        ('quiz', '0003_quiztemplate_shuffle_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('rich_text', 'Rich text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('quiz', 'Quiz'), ('callout', 'Callout'), ('code', 'Code'), ('embed', 'Embed')], max_length=16)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lms/blocks/img/')),
                ('video_url', models.URLField(blank=True)),
                ('video_provider', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('upload', 'Self-hosted')], max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='lms/blocks/file/')),
                ('external_url', models.URLField(blank=True)),
                ('code_language', models.CharField(blank=True, max_length=32)),
                ('code_content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='lms_catalog.lesson')),
                ('quiz_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_blocks', to='quiz.quiztemplate')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContentBlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('rich_text', models.TextField(blank=True, verbose_name='rich text')),
                ('callout_text', models.TextField(blank=True, verbose_name='callout text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lms_catalog.contentblock')),
            ],
            options={
                'verbose_name': 'content block Translation',
                'db_table': 'lms_catalog_contentblock_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='uniq_block_order_per_lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='contentblocktranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
