# Generated by Django 6.0.4 on 2026-04-15 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz', to='domain.domain')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAlertThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('question', 'Question'), ('assignment', 'Assignment')], default='question', max_length=16)),
                ('reported_language', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('reporter_reply_allowed', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('reporter_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('owner_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_quiz_alert_threads', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_quiz_alert_threads', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_threads', to='quiz.quiz')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_quiz_alert_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAlertMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_alert_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='quiz.quizalertthread')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Poids de la question dans le score.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='question.question')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='quizalertthread',
            name='quizquestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_threads', to='quiz.quizquestion'),
        ),
        migrations.CreateModel(
            name='QuizTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Titre du quiz')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('exam', 'Examen')], default='practice', max_length=10)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('max_questions', models.PositiveIntegerField(default=10, help_text='Nombre de questions à poser parmi le pool lié.', verbose_name='Nombre de questions dans le quiz')),
                ('permanent', models.BooleanField(default=True, verbose_name='Permanent ?')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('with_duration', models.BooleanField(default=True, verbose_name='Avec Timer ?')),
                ('duration', models.PositiveIntegerField(default=10, verbose_name='temps (en minutes)')),
                ('result_visibility', models.CharField(choices=[('immediate', 'Immédiat'), ('scheduled', "À partir d'une date"), ('never', 'Jamais')], default='immediate', help_text="Quand le score global du quiz peut être affiché à l'utilisateur.", max_length=10, verbose_name='Visibilité du résultat global')),
                ('result_available_at', models.DateTimeField(blank=True, help_text="Utilisé uniquement si la visibilité est 'À partir d'une date'.", null=True, verbose_name='Résultat global visible à partir de')),
                ('detail_visibility', models.CharField(choices=[('immediate', 'Immédiat'), ('scheduled', "À partir d'une date"), ('never', 'Jamais')], default='immediate', help_text="Quand les réponses détaillées (réponses de l'utilisateur et bonnes réponses) peuvent être affichées.", max_length=10, verbose_name='Visibilité du détail des réponses')),
                ('detail_available_at', models.DateTimeField(blank=True, help_text="Utilisé uniquement si la visibilité est 'À partir d'une date'.", null=True, verbose_name='Détail visible à partir de')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public ?')),
                ('active', models.BooleanField(default=True, verbose_name='Actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_templates', to='domain.domain')),
                ('questions', models.ManyToManyField(related_name='question', through='quiz.QuizQuestion', to='question.question', verbose_name='Pool de quizquestions')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.quiztemplate'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.quiztemplate'),
        ),
        migrations.CreateModel(
            name='QuizQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField()),
                ('given_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('earned_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quiz')),
                ('quizquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizquestion')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='quiz_answers', to='question.answeroption')),
            ],
            options={
                'ordering': ['quiz', 'question_order'],
                'constraints': [models.UniqueConstraint(fields=('quiz', 'quizquestion'), name='uniq_answer_per_quiz_question')],
                'unique_together': {('quiz', 'question_order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'question'), ('quiz', 'sort_order')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['user', 'active'], name='quiz_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['user', '-created_at'], name='quiz_user_created_idx'),
        ),
    ]
