# Generated by Django 6.0.4 on 2026-06-01 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_domain_certificate_logo_and_more'),
        ('quiz', '0003_quiztemplate_shuffle_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['quiz_template', '-created_at'], name='quiz_template_created_idx'),
        ),
    ]
