# Generated by Django 6.0.4 on 2026-04-09 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_domain_updated_by'),
        ('quiz', '0004_quiztemplate_translations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['user', 'active'], name='quiz_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['user', '-created_at'], name='quiz_user_created_idx'),
        ),
    ]
