# Generated by Django 5.2.8 on 2026-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroptiontranslation',
            name='content',
            field=models.TextField(max_length=4000, verbose_name='possible answer'),
        ),
        migrations.AlterField(
            model_name='questiontranslation',
            name='description',
            field=models.TextField(blank=True, max_length=4000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='questiontranslation',
            name='explanation',
            field=models.TextField(blank=True, max_length=4000, verbose_name='Explanation'),
        ),
    ]
