# Generated by Django 6.0.4 on 2026-05-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
