# Generated by Django 6.0.4 on 2026-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_domaininvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainjoinrequest',
            name='expiry_warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
