# Generated by Django 6.0.4 on 2026-04-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_rename_staff_to_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='join_policy',
            field=models.CharField(choices=[('auto', 'Automatic'), ('owner', 'Owner validation'), ('owner_managers', 'Owner or managers validation')], default='auto', max_length=20),
        ),
    ]
