# Generated by Django 6.0.4 on 2026-05-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_domainjoinrequest_expiry_warning_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
