# Generated by Django 6.0.4 on 2026-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_domain_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='certificate_logo',
            field=models.ImageField(blank=True, null=True, upload_to='domain/certificate-logos/'),
        ),
        migrations.AddField(
            model_name='domain',
            name='certificate_signatory_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='domaintranslation',
            name='certificate_signatory_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='certificate signatory title'),
        ),
    ]
