# Generated by Django 6.0.6 on 2026-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_domain_certificate_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='reviews_allow_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='reviews_allow_rating',
            field=models.BooleanField(default=True),
        ),
    ]
