# Generated by Django 6.0.7 on 2026-07-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_domain_reviews_allow_comment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domaintranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='domaintranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='domain_domain_translation_uniq_lang'),
        ),
    ]
