# Generated by Django 6.0.6 on 2026-07-26 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0007_domain_certificate_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=8)),
                ('free_until', models.DateTimeField(blank=True, null=True)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('member_count_updated_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_14d_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_3d_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='domain.domain')),
            ],
        ),
    ]
