# Generated by Django 6.0.4 on 2026-05-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_blocks_from_richtext'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mediaasset',
            name='question_me_kind_3d8677_idx',
        ),
        migrations.RemoveConstraint(
            model_name='mediaasset',
            name='uniq_mediaasset_kind_sha256_notnull',
        ),
        migrations.RemoveConstraint(
            model_name='questionmedia',
            name='uniq_question_media_asset',
        ),
        migrations.RemoveField(
            model_name='questionmedia',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='questionmedia',
            name='question',
        ),
        migrations.DeleteModel(
            name='MediaAsset',
        ),
        migrations.DeleteModel(
            name='QuestionMedia',
        ),
    ]
