# Generated by Django 6.0.4 on 2026-04-11 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_rename_staff_to_managers'),
        ('question', '0003_question_updated_by'),
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['domain', 'active'], name='question_domain_active_idx'),
        ),
    ]
