# Generated by Django 6.0.7 on 2026-07-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_mediaasset_question_me_kind_3d8677_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questiontranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='questiontranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='question_question_translation_uniq_lang'),
        ),
    ]
