# Generated by Django 6.0.4 on 2026-04-15 14:24

import question.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_add_domain_active_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=question.models.media_asset_upload_to),
        ),
    ]
