# Generated by Django 6.0.4 on 2026-06-03 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.CharField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('login_method', models.CharField(choices=[('password', 'Password'), ('magic_link', 'Magic link')], default='password', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=120)),
                ('os', models.CharField(blank=True, max_length=120)),
                ('local_time', models.CharField(blank=True, max_length=64)),
                ('browser_language', models.CharField(blank=True, max_length=64)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True)),
                ('screen_height', models.PositiveIntegerField(blank=True, null=True)),
                ('online', models.BooleanField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=180)),
                ('region', models.CharField(blank=True, max_length=180)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='connlog_user_created_idx')],
            },
        ),
    ]
